[project]
name = "robo-ttt"
version = "0.1.2"
description = "RoboTTT - Context Scaling for Robot Policies"
authors = [
    { name = "Phil Wang", email = "lucidrains@gmail.com" }
]
readme = "README.md"
requires-python = ">= 3.10"
license = { file = "LICENSE" }
keywords = [
    'artificial intelligence',
    'deep learning',
    'robotics',
    'test-time training',
    'context scaling'
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    "einx>=0.3.0",
    "einops>=0.8.1",
    "rotary-embedding-torch",
    "torch>=2.5",
    "torch-einops-utils>=0.1.12"
]

[project.urls]
Homepage = "https://pypi.org/project/robo-ttt/"
Repository = "https://codeberg.org/lucidrains/robo_ttt"

[project.optional-dependencies]
examples = []
test = [
    "pytest",
    "mimic-video>=0.3.11",
    "pi-zero-pytorch>=0.5.11"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = [
    "robo_ttt",
    "pyproject.toml",
    "README.md",
    "LICENSE"
]

[tool.hatch.build.targets.wheel]
packages = ["robo_ttt"]
